# Generated by Django 4.2.1 on 2023-10-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user_id",
            new_name="user",
        ),
    ]
